version: '3'

services:

  basic-sanic-app:
    container_name: basic-sanic-app
    build: ${PROJECTS_HOME}/basic-sanic-app
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
      - "8000:8000"
    volumes:
    - ${PROJECTS_HOME}/basic-sanic-app
    networks:
      - test-env

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    environment: 
      - WATCHTOWER_NOTIFICATIONS = slack
      - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL = "https://hooks.slack.com/services/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"
      - WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER = watchtower-server-1
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 10 --label-enable
    networks:
      - test-env

networks:
  test-env:
    driver: bridge
